name: Terragrunt Apply
on:
  push:
    branches:
      - main
permissions: 
    id-token: write
    contents: write
jobs:
  terragrunt_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Install Terragrunt
        run: |
            wget -q -O /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.30.0/terragrunt_linux_amd64
            chmod +x /tmp/terragrunt
            sudo mv /tmp/terragrunt /usr/local/bin/terragrunt
            terragrunt --version  # Verify installation
      - name: Set Environment Variables
        working-directory: .
        run: |
              echo AWS_REGION="eu-central-1" >> $GITHUB_ENV
              export AWS_ACCOUNT_ID="742500315313"
              echo AWS_ROLE="arn:aws:iam::767398139787:role/github-oidc-role" >> $GITHUB_ENV
      - name: Display AWS Environment Variables
        run: |
            echo "AWS Environment Variables:"
            env | grep ^AWS

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
              role-to-assume: arn:aws:iam::767398139787:role/github-oidc-role
              aws-region: eu-central-1
      - name: Print assumed role
        run: aws sts get-caller-identity
      - name: Init Terraform
        working-directory: ./environments/test
        run: terragrunt init 
      - name: apply Terraform
        working-directory: ./environments/test
        run: |
         terragrunt apply -auto-approve